version: '3.8' 

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "txn.commands:1:1,txn.events:1:1,txn.dlq:1:1"

  backend-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_api
    environment:
      - SERVICE_ROLE=api
      - KAFKA_BROKER=kafka:29092
    ports:
      - "3000:3000"
    depends_on:
      - kafka
    entrypoint: ["./wait-for-kafka.sh", "/app/backend_bin"]

  backend-orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_orchestrator
    environment:
      - SERVICE_ROLE=orchestrator
      - KAFKA_BROKER=kafka:29092
    depends_on:
      - kafka
    entrypoint: ["./wait-for-kafka.sh", "/app/backend_bin"]

  backend-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_gateway
    environment:
      - SERVICE_ROLE=gateway
      - KAFKA_BROKER=kafka:29092
    ports:
      - "8080:8080"   
      - "9090:9090"   
    depends_on:
      - kafka
    entrypoint: ["./wait-for-kafka.sh", "/app/backend_bin"]
